In [1]:
import scrapy

In [2]:
from scrapy.crawler import CrawlerProcess

In [3]:
import numpy

In [4]:
l=[23245,27,546,245,-1234]

In [5]:
l

[23245, 27, 546, 245, -1234]

In [6]:
import numpy as np

In [7]:
a=np.array(l)

In [8]:
a

array([23245,    27,   546,   245, -1234])

In [13]:
b=np.array(['12','455','63.3','True',"abc",])

In [14]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U4')

In [15]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [17]:
l.pop()

-1234

In [18]:
a.mean()

4565.8

In [19]:
#---------------------

In [20]:
a

array([23245,    27,   546,   245, -1234])

In [21]:
a[2:]

array([  546,   245, -1234])

In [22]:
a[2:4]

array([546, 245])

In [23]:
b[0]

'12'

In [24]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U4')

In [27]:
c=a.copy()

In [28]:
c

array([23245,    27,   546,   245, -1234])

In [29]:
a

array([23245,    27,   546,   245, -1234])