# Import the relevant libraries

In [1]:
import numpy as np

# Declaring the scalars, vectors and matrices

## Scalars

In [2]:
s=5

In [3]:
s

5

## Vectors

In [5]:
V = np.array([5,-2,4])

In [6]:
V

array([ 5, -2,  4])

## Matrices

In [8]:
m = np.array([[5,12,6],[-3,0,14]])

In [9]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data Types

In [10]:
type(s)

int

In [11]:
type(V)

numpy.ndarray

In [12]:
type(m)

numpy.ndarray

In [13]:
s_array = np.array(5)
s_array

array(5)

In [14]:
type(s_array)

numpy.ndarray

## Data Shapes

In [15]:
m.shape

(2, 3)

In [16]:
V.shape

(3,)

In [17]:
V.reshape(1,3)

array([[ 5, -2,  4]])

In [18]:
V.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [19]:
s_array.shape

()

## Creating a tensor

In [20]:
n1 = np.array([[5,12,6],[-3,0,14]])
n1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [21]:
n2 = np.array([[9,8,7],[1,3,-5]])
n2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [22]:
t = np.array([n1,n2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Checking its shape

In [23]:
t.shape

(2, 2, 3)

## Manually creating tensor

In [24]:
t_manual = np.array([[[5,12,6],[-3,0,14],[1,3,-5]]])

In [25]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14],
        [ 1,  3, -5]]])

## Addition

In [26]:
n1 = np.array([[5,12,6],[-3,8,14]])
n1

array([[ 5, 12,  6],
       [-3,  8, 14]])

In [27]:
n2 = np.array([[9,8,7],[1,3,-5]])
n2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [28]:
n1+n2

array([[14, 20, 13],
       [-2, 11,  9]])

In [29]:
n3 = np.array([[5,3],[-2,4]])
n4 = np.array([[7,-5],[3,8]])

In [30]:
n3

array([[ 5,  3],
       [-2,  4]])

In [31]:
n4

array([[ 7, -5],
       [ 3,  8]])

In [32]:
n3-n4

array([[-2,  8],
       [-5, -4]])

In [33]:
n1*n2

array([[ 45,  96,  42],
       [ -3,  24, -70]])

In [34]:
n1/n2

array([[ 0.55555556,  1.5       ,  0.85714286],
       [-3.        ,  2.66666667, -2.8       ]])

## Adding the vectors

In [35]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [36]:
v1+v2

array([6, 6, 6, 6, 6])

In [37]:
v2-v1

array([ 4,  2,  0, -2, -4])

In [38]:
v1-v2

array([-4, -2,  0,  2,  4])

## Addition of Scalars (Exception)

In [39]:
n1

array([[ 5, 12,  6],
       [-3,  8, 14]])

In [40]:
n1+1

array([[ 6, 13,  7],
       [-2,  9, 15]])

In [41]:
V

array([ 5, -2,  4])

In [42]:
n2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [43]:
n2+1

array([[10,  9,  8],
       [ 2,  4, -4]])

In [44]:
v1

array([1, 2, 3, 4, 5])

In [45]:
v1+1

array([2, 3, 4, 5, 6])

In [47]:
n1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  9, 15]])

In [48]:
v1+np.array([1])

array([2, 3, 4, 5, 6])

# Transposing Matrices

In [50]:
A= np.array([[5,12,6],[-3,0,24]])
A

array([[ 5, 12,  6],
       [-3,  0, 24]])

In [51]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 24]])

In [52]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [53]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [54]:
C = np.array([[4,5],[8,12],[10,0]])
C

array([[ 4,  5],
       [ 8, 12],
       [10,  0]])

In [55]:
C.T

array([[ 4,  8, 10],
       [ 5, 12,  0]])

## Transposing Scalars

In [56]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [57]:
x.T

array([1, 2, 3])

In [58]:
x.shape

(3,)

In [61]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [62]:
x_reshaped.T

array([[1],
       [2],
       [3]])

# Dot Product

In [65]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [66]:
np.dot(x,y)

-66

In [67]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [68]:
np.dot(u,v)

18

## Scalar * Scalar

In [69]:
np.dot(5,6)

30

In [70]:
np.dot(10,-2)

-20

# Scalar * Vector

In [71]:
x

array([ 2,  8, -4])

In [72]:
5*x

array([ 10,  40, -20])

# Scalar * Matrix

In [73]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [74]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

In [75]:
c= np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
c

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [76]:
d = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
d

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [77]:
np.dot(c,d)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])